### ISSUE TITLE
Daemon start error [release]

### ISSUE THREAD

**Issue by aistrych** [Pink2Dev/Pink2#12]
Platform: Windows 10

Daemon embedded in Pinkcoin-Win64-2.2.0.0.zip throws error claiming that it can't find that file:
```
 libwindpthread-1.dll
```

**Comment by JRedinger** [comment]
I'll check out the build script and see if I can get that fixed once I get home. Should be fixed by tonight. Thanks!

**Comment by JRedinger** [comment]
Fixed the build script and updated the pink2d.exe binary. Confirmed bug and fix on Windows 7. Should work fine on Windows 10 now. Please confirm and close thread if it's all good on your end as well.

**Comment by aistrych** [comment]
Yes, I can confirm. Works great. Thanks.
