### ISSUE TITLE
Pi wallet Passphrase compromised

### ISSUE THREAD

**Issue by HassaN99663** [Pink2Dev/Pink2#41]
Hi my pi wallet Passphrase is compromised,person transfer all available coins to his wallet.
My lockup coins coming in a year, I want to save them with an automated script to transfer coming coins to my other wallet before the hacker, can anyone help?

**Comment by Toshmach** [comment]
> Hi my pi wallet Passphrase is compromised,person transfer all available coins to his wallet. My lockup coins coming in a year, I want to save them with an automated script to transfer coming coins to my other wallet before the hacker, can anyone help?

Hey @HassaN99663 ,
If your issue hasn’t been resolved yet, I suggest contacting the support team for specialized assistance.
A support ticket has been created for you with ID PII7638. Visit [Pi Wallet Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat bubble in the bottom right to connect with an agent for quick help.
Thank you for your patience—I’m confident this will be resolved.

**Comment by tranzium** [comment]
Appreciate you reaching out @HassaN99663 

However, Pi is not associated with Pinkcoin.

Please use the Pi application or Pi Browser application for support.
